### ISSUE TITLE
Failure to load login page, is 403 Forbidden

### ISSUE THREAD

**Issue by chrisjbillington** [kajchang/runkeeper#2]
I'm getting the following traceback when trying to log in:
```python
Traceback (most recent call last):
  File "download.py", line 12, in <module>
    account = Account(email, password)
  File "runkeeper/runkeeper/Account.py", line 15, in __init__
    parse.urlparse(landing_page.find(class_='log-in').find('a')['href'][27:-2]).query)
AttributeError: 'NoneType' object has no attribute 'find'
```

Further investigation reveals that `landing_page` is a 403 error page:
```html
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr/><center>nginx</center>
</body>
</html>
```

A quick google indicates that this might be due to the server rejecting clients that look like bots, for example if they don't specify a user-agent. I tried adding a generic user-agent header but to no avail
```diff
diff --git a/runkeeper/Account.py b/runkeeper/Account.py
index 752d94d..669476d 100644
--- a/runkeeper/Account.py
+++ b/runkeeper/Account.py
@@ -5,12 +5,18 @@ from urllib import parse

 from .User import User

+headers = {
+    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
+}

 class Account(User):
     def __init__(self, email: str, password: str):
         session = requests.Session()

-        landing_page = BeautifulSoup(session.get('https://runkeeper.com').text, 'html.parser')
+        landing_page = BeautifulSoup(
+            session.get('https://runkeeper.com', headers=headers).text, 'html.parser'
+        )
+
         login_query_string = parse.parse_qs(
             parse.urlparse(landing_page.find(class_='log-in').find('a')['href'][27:-2]).query)
```

Perhaps specifying more headers to better emulate a real browser is required.

**Comment by kaijchang** [comment]
@chrisjbillington yeah, I think you're probably on the right track. I can look into it more tomorrow. It was working in April, but these sorts of unofficial tools are really not resistant to any sort of change on their side so thanks for spotting this.

**Comment by kaijchang** [comment]
@chrisjbillington I think I fixed the issue, tell me if you run into any more problems.

**Comment by chrisjbillington** [comment]
Thank you very much for the quick fix!

Can verify the fix works for me.
